export { default as LandingPage } from './pages/landing/LandingPage';
export { AdvancedMarketingPage } from './pages/marketing/AdvancedMarketingPage';
export { default as MarketingStubPage } from './pages/marketing/MarketingStubPage';

export { default as AboutPage } from './pages/About';
export { Features } from './pages/Features';
export { default as FeatureDetailPage } from './pages/FeatureDetail';
export { default as PricingPage } from './pages/Pricing';
export { default as BlogPage } from './pages/Blog';
export { default as BlogPostPage } from './pages/BlogPost';
export { default as FAQPage } from './pages/FAQ';
export { default as ContactPage } from './pages/Contact';
export { default as PrivacyPage } from './pages/Privacy';
export { default as TermsPage } from './pages/Terms';
export { default as NotFoundPage } from './pages/NotFound';
export { default as DemoPage } from './pages/Demo';
export { default as PressPage } from './pages/Press';
export { default as CookiesPage } from './pages/Cookies';
export { default as SystemStatusPage } from './pages/SystemStatus';
export { default as CommunityPage } from './pages/Community';
export { default as SecurityOverviewPage } from './pages/SecurityOverview';
export { default as HelpPage } from './pages/Help';
export { default as ResourcesPage } from './pages/Resources';

export { default as ResourceGuidePage } from './pages/resources/Guide';
export { default as ResourceVideosPage } from './pages/resources/Videos';
export { default as ResourceCaseStudiesPage } from './pages/resources/CaseStudies';
export { default as ResourcePromptsPage } from './pages/resources/Prompts';
export { default as ResourceWebinarsPage } from './pages/resources/Webinars';
export { default as ResourceNewsletterPage } from './pages/resources/Newsletter';
